### ISSUE TITLE
Build fails due to undefined references

### ISSUE THREAD

**Issue by AmnonOwed** [madc/ofxVoronoi#1]
I have a problem building this ofx addon with OF 0.8.4. on Windows 8 64-bit using Code::Blocks 13:12. I have generated a project from the included example with the projectGenerator. It seems correct, but unfortunately it runs into 7 build errors (all undefined references). My attemps to fix this have not worked out. I would like to use your voronoi implementation, because out of the three I found, it is the only one that allows you to get the voronoi cells easily.

The 7 build errors are:

```
obj\Release\addons\ofxVoronoi\src\ofxVoronoi.o:ofxVoronoi.cpp|| undefined reference to `voro::container_2d::container_2d(double, double, double, double, int, int, bool, bool, int)'|
obj\Release\addons\ofxVoronoi\src\ofxVoronoi.o:ofxVoronoi.cpp|| undefined reference to `voro::voronoicell_base_2d::voronoicell_base_2d()'|
obj\Release\addons\ofxVoronoi\src\ofxVoronoi.o:ofxVoronoi.cpp|| undefined reference to `voro::container_2d::put(int, double, double)'|
obj\Release\addons\ofxVoronoi\src\ofxVoronoi.o:ofxVoronoi.cpp|| undefined reference to `bool voro::voro_compute_2d<voro::container_2d>::compute_cell<voro::voronoicell_2d>(voro::voronoicell_2d&, int, int, int, int)'|
obj\Release\addons\ofxVoronoi\src\ofxVoronoi.o:ofxVoronoi.cpp|| undefined reference to `voro::container_base_2d::~container_base_2d()'|
obj\Release\addons\ofxVoronoi\src\ofxVoronoi.o:ofxVoronoi.cpp|| undefined reference to `voro::voronoicell_base_2d::~voronoicell_base_2d()'|
obj\Release\addons\ofxVoronoi\src\ofxVoronoi.o:ofxVoronoi.cpp|| undefined reference to `voro::voronoicell_base_2d::~voronoicell_base_2d()'|
```

**Comment by madc** [comment]
I've to admit, i´m not really familiar with OF on windows and have therefor only tested the addon on OSX. It is basically a wrapper for the Voro++2D library and it looks like this library is not linked to your project probably. You can find it in the [libs/Voro++2D](https://github.com/madc/ofxVoronoi/tree/master/libs/Voro%2B%2B2D) folder. (See [FAQ-Compiling (errors) / Q: My build fails with multiple undefined reference errors? ](http://wiki.codeblocks.org/index.php?title=FAQ-Compiling_%28errors%29))

Let me know, if this solves your issue. Otherwise let me know, what you've tried. I've a windows machine somewhere at the office, i can check on this later next week.

**Comment by AmnonOwed** [comment]
Thanks for your reply. Let me admit that I have only used OpenFrameworks and C++ for a month, so I am somewhat unfamiliar with these kind of issues. But learning fast... ;-)

It seems the libs/Voro++2D folder contains both the static .a library and the .hh files. I tried linking either.
1. Project > Build options > Linker settings | Link libraries | Add : libvoro++_2d32.a. I don't think this works, it results in 1 error referring to a syntax error. I guess that's just because it expects a different kind of file. Perhaps static libraries should be linked differently, but spending some time googling this, didn't help me to find another way. The full error is: _c:\coding\codeblocks\mingw\bin..\lib\gcc\mingw32\4.7.1........\mingw32\bin\ld.exe:..\libs\Voro++2D\libvoro++_2d32.a|1|syntax error|_
2. Project > Build options > Linker settings | Link libraries | Add : all the .hh files (not the .a file). I get two errors in rad_option.hh that sqrt was not defined in this scope. I can fix this by #including math.h. Then the app actually compiles, but I get a warning (translated): "Not supported 16-bit application" and "Program can't be started because of incompatibilty with 64-bit windows." I am unsure if this means I have succesfully linked/compiled, but ran into another issue or that something went wrong with linking/compiling, resulting in this issue.

Will add more information, if I find anything. If you could try it out, that would be appreciated.

**Comment by madc** [comment]
Having some troubles to get OF running on windows. Could you try, if [vanderlin/ofxVoronoi](https://github.com/vanderlin/ofxVoronoi) works for you? If that's the case, i think i've got a vast idea whats wrong.

**Comment by AmnonOwed** [comment]
Nope, vanderlin's version doesn't work, but imho it has a folder structure that looks completely wrong.

I have tried [obviousjim/ofxDelaunay](https://github.com/obviousjim/ofxDelaunay), which is similar and has a correct folder structure. When I use the projectGenerator on ofxDelaunay, it does create a working project. I've tried emulating ofxDelaunay's folder structure for your addon, but it still shows the undefined references when trying to compile.

Could it be somehow related to the extensions? The non-working .a and .hh versus the working .h and .cpp? Or to the code in the Voro++2D library's files?

**Comment by AmnonOwed** [comment]
Ok, more relevant information. I tried [patriciogonzalezvivo/ofxVoro](https://github.com/patriciogonzalezvivo/ofxVoro). This addon also uses the voro++ library. I applied the PG to both included examples and both of them worked right away.

**Comment by madc** [comment]
That's good to know. I'll have some spare time on Friday to look into it. Keep me posted, if you find something new.

**Comment by AmnonOwed** [comment]
I tried emulating ofxVoro's point to a single .hh file (instead of several), but that didn't solve it either. I notice an apparant difference between ofxVoro and ofxVoronoi examples after running the PG. The former shows a list of files from the lib in the .cbp project file and thus also in the workspace in CB. However the latter shows nothing, it ain't in the project file and thus also not in the workspace. Hence the missing references issue. The listed files are all the .cc files (not the .hh files), so I think this might be related to the fact that the 2D lib included with your and vanderlin's addon does not include .cc files but instead only a .a file. Do you know if there is a 2D library with .cc files, so I could test this hypothesis? On the linked website I see many older downloads, but no specific mentions of a 2D library.

For completeness, this is what is shown in the .cbp file of a working ofxVoro example:

```
        <Unit filename="../../../addons\ofxVoro\libs\voro++\cell.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\common.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\container.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\container_prd.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\c_loops.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\pre_container.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\unitcell.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\v_base.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\v_compute.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
        <Unit filename="../../../addons\ofxVoro\libs\voro++\wall.cc">
            <Option virtualFolder="addons\ofxVoro\libs\voro++" />
        </Unit>
```

When I remove the above lines from the ofxVoro example project file and try to compile, I get exactly the same kind of undefined reference errors as with ofxVoronoi.

When I add the following, similar lines to the ofxVoronoi example project, the file shows up correctly in the workspace view.

```
        <Unit filename="../../../addons\ofxVoronoi\libs\Voro++2D\libvoro++_2d32.a">
            <Option virtualFolder="addons\ofxVoronoi\libs\Voro++2D" />
        </Unit>
```

However, when I try to compile it, I get an error that says:

```
 obj\Release\addons\ofxVoronoi\libs\Voro++2D\libvoro++_2d32.o||No such file or directory|
```

So that indicates again, that there is a problem finding, compiling, using the .a file.

**Comment by AmnonOwed** [comment]
So today I tried making changes to the addon's folder structure to adhere to the guidelines for ofxaddons as described [here](http://www.ofxaddons.com/howto/#make) and [here](https://github.com/openframeworks/ofxAddonTemplate/tree/master/libs/necessaryLib/lib/win_cb). This results in a few extra lines in the .cbp project pointing towards the static library's folders (a good sign). However, I also get a familiar (see third message, bullit 1) build error: _c:\coding\codeblocks\mingw\bin..\lib\gcc\mingw32\4.7.1........\mingw32\bin\ld.exe:......\addons\ofxVoronoi\libs\Voro++2D\lib\win_cb\libvoro++_2d32.a|1|syntax error|_

Once again, I feel that the .a static library is causing most of the problems.

**Comment by AmnonOwed** [comment]
Found a version of the 2D library [here](https://github.com/slowriot/voro--/tree/master/branches/2d/src) with .cc files and apparantly some relatively recent fixes, but I couldn't quite make it work.

**Comment by madc** [comment]
Sorry for not coming back to you in time. I've been (and still are for this week) busy. I'll try to look into it this week. Thanks for finding the actual library. Btw, i'd be willing to switch to another voronoi lib in a heartbeat, if we find one.

**Comment by AmnonOwed** [comment]
Great. Still haven't found a way to make it work.

It seems there aren't any promising 2D voronoi library alternatives to use for the ofxaddon. There is [libvoronoi](http://libvoronoi.sourceforge.net/), but it hasn't been updated in over a decade. And there is [openvoronoi](https://github.com/aewallin/openvoronoi), but it has several dependencies itself. Perhaps an [updated 2D implementation](http://stackoverflow.com/a/15853719) of the voro++ library by it's original author is still the preferable option.

**Comment by AmnonOwed** [comment]
I think a custom **addon_config.mk** (such as [this one for ofxKinect](https://github.com/ofTheo/ofxKinect/blob/master/addon_config.mk)) might be needed for the static .a library to be recognised correctly under different platforms (in my case win_cb).

**Comment by madc** [comment]
I've been playing around with the source from the repo, you mentioned above, but couldn't quite make it run. Have you tried adding a addon_config.mk locally? ([Here is the most complete example i could find](https://github.com/arturoc/ofxGStreamer/blob/master/addon_config.mk))

**Comment by AmnonOwed** [comment]
I have tried it and it definitely affects the way the PG operates. For example I added the following line in the addon_config.mk file: **ADDON_SOURCES = ../../../addons/ofxVoronoi/libs/Voro++2D/libvoro++_2d32.a**

I then see this file show up in the cb workspace. However when I try to compile I run into the same error I got on february 3rd when I tried to manually add the .a file to the workspace: **obj\Release\addons\ofxVoronoi\libs\Voro++2D\libvoro++_2d32.o||No such file or directory**

Alternatively, I tried adding all the other files via the addon_config.mk file. I see them show up in the cb workspace, but I get the same 'undefined reference' errors I started with.

So the good news is that addon_config.mk can surely be used to finetune the way the PG creates a runnable project from the source files. The bad news is that after one and a half month of attempts, it still does not run.

**Comment by madc** [comment]
I still could not make OF run on my windows machine and will be abroad for the next month. Could you post this to the OF forum and link it here?

**Comment by AmnonOwed** [comment]
Some of the analysis above was in the right direction. The golden tip and solution came about via the OF forum (big thanks to @trentbrooks!) and it was to replace the library files. I have just sent a pull request (tested & working) which implements the solution. For more information, see the pull request.

**Comment by madc** [comment]
Again, thanks for sticking on the issue and solving it.
