### ISSUE TITLE
where is the ofmian.h?

### ISSUE THREAD

**Issue by heguohao0728** [madc/ofxVoronoi#8]
where is the ofmian.h?

**Comment by nosarious** [comment]
If main is part of openframeworks. You may have a different folder system than the creator of this library.

Try the suggestions mentioned here: https://forum.openframeworks.cc/t/ofxtween-ofmain-h-not-found/15152

**Comment by heguohao0728** [comment]
Thank you so much.

**Comment by heguohao0728** [comment]
But my result is like this......Why was that?
![image](https://user-images.githubusercontent.com/54935494/66478801-c96bef00-eacd-11e9-96d2-5206a0be19c9.png)
